import Foundation

enum CH57xConfigurationError: LocalizedError, Equatable {
    case unsupportedDeferredAction(HardwareControl)
    case invalidExpression(HardwareControl, String)
    case sequenceTooLong(HardwareControl)

    var errorDescription: String? {
        switch self {
        case .unsupportedDeferredAction(let control):
            AppLanguage.text(
                "\(control.title) nutzt eine lokale/deeplink-basierte Aktion. Sie benötigt einen späteren F13–F21-Listener und kann nicht direkt auf das Gerät geladen werden.",
                "\(control.title) uses a local or deep-link action. It requires a later F13–F21 listener and cannot be transferred to the device directly."
            )
        case .invalidExpression(let control, let expression):
            AppLanguage.text(
                "Ungültiger Ausdruck für \(control.title): \(expression)",
                "Invalid expression for \(control.title): \(expression)"
            )
        case .sequenceTooLong(let control):
            AppLanguage.text(
                "\(control.title) enthält mehr als fünf Tastenkombinationen; 0x8890 unterstützt höchstens fünf.",
                "\(control.title) contains more than five key combinations; the 0x8890 supports at most five."
            )
        }
    }
}

struct CH57xConfigurationEncoder {
    func encode(profile: MacropadProfile) throws -> String {
        let top = try [HardwareControl.key1, .key2, .key3].map { try yamlValue(for: profile.action(for: $0), control: $0) }
        let bottom = try [HardwareControl.key4, .key5, .key6].map { try yamlValue(for: profile.action(for: $0), control: $0) }
        let ccw = try yamlValue(for: profile.action(for: .encoderLeft), control: .encoderLeft)
        let press = try yamlValue(for: profile.action(for: .encoderPress), control: .encoderPress)
        let cw = try yamlValue(for: profile.action(for: .encoderRight), control: .encoderRight)

        return """
        # Generated by Agent Micro. Do not edit while an upload is in progress.
        model: ch57x-2
        orientation: normal
        rows: 2
        columns: 3
        knobs: 1
        layers:
          - buttons:
              - [\(top.joined(separator: ", "))]
              - [\(bottom.joined(separator: ", "))]
            knobs:
              - ccw: \(ccw)
                press: \(press)
                cw: \(cw)
        """
    }

    private func yamlValue(for action: KeyboardAction, control: HardwareControl) throws -> String {
        guard action.kind != .disabled else { return "null" }
        guard action.kind.isDirectlySupportedByDevice else { throw CH57xConfigurationError.unsupportedDeferredAction(control) }
        guard let expression = action.deviceMacro?.trimmingCharacters(in: .whitespacesAndNewlines), !expression.isEmpty else {
            return "null"
        }
        guard !expression.contains("\n"), !expression.contains("\r"), !expression.contains("\0") else {
            throw CH57xConfigurationError.invalidExpression(control, expression)
        }
        guard expression.split(separator: ",").count <= 5 else { throw CH57xConfigurationError.sequenceTooLong(control) }
        return "'\(expression.replacingOccurrences(of: "'", with: "''"))'"
    }
}
